import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
const AblyChatComponent = dynamic(
  () => import("../components/AblyChatComponent"),
  { ssr: false }
);

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>beatstreet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://beatstreet.dance">beatstreet</a>
        </h1>

        <p className={styles.description}>Underground Dance Music Nonstop </p>

        <iframe
          className={styles.card}
          src="https://fm.soundzmuzicradio.com/public/soundzmuzicradio/embed?theme=dark"
          frameBorder="1"
          style={{ minHeight: 100, minWidth: "70%", border: 0 }}
        ></iframe>
        <iframe
          src="https://fm.soundzmuzicradio.com/public/soundzmuzicradio/history?theme=dark"
          frameBorder="0"
          style={{ minHeight: 150, minWidth: "70%" }}
        ></iframe>
        <div className={styles.card}>
          <AblyChatComponent />{" "}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
